### ISSUE TITLE
cl_editor doesn't do anything

### ISSUE THREAD

**Issue by Panjoo** [jdolan/quetoo#477]
At least here on Win732bit MinGW, the cl_editor is broken. It lets me open the editor but the soon as I touch a slider it crashes with a signal11.

**Comment by kaadmy** [comment]
Is there a specific map/face that triggers this, or everything?
This might have been caused by the material refactor changes.

**Comment by kaadmy** [comment]
Yeah, this seems to only happen on faces that don't have a material, ie `sandbox`s floor.

**Comment by Panjoo** [comment]
This happens on every map I've tried so far. It shows the material and the values. Soon as I touch sliders it's *plop*.

![quetoo068](https://cloud.githubusercontent.com/assets/10857572/26180512/3211db48-3b6a-11e7-8858-f8f68bcd7ef8.jpg)

**Comment by kaadmy** [comment]
Hm, I can reproduce this on Edge and Tokays now.

**Comment by Paril** [comment]
Any stack traces?

**Comment by kaadmy** [comment]
Should be good now, I think I changed how slider delegates worked in ObjectivelyMVC some time after I implemented the editor.

**Comment by Panjoo** [comment]
This is not fixed yet...

cl_editor is not crashing anymore but the sliders don't affect the material settings at all.

![noeffect](https://cloud.githubusercontent.com/assets/10857572/26207026/b0f391e6-3be6-11e7-95ac-02684c5edec3.jpg)

**Comment by kaadmy** [comment]
Hm, it seems the issue is that the materials aren't updated, so this is possibly related to the recent material refactor.

**Comment by kaadmy** [comment]
@jdolan bump?

**Comment by jdolan** [comment]
Have not had a chance to look into it. Traveling this coming week for work. Maybe next weekend.

**Comment by jdolan** [comment]
This was a regression due to (incorrect) delegate changes in ObjectivelyMVC. All set now.
